### ISSUE TITLE
Some ASB bundles such as postgresql db are blacklisted

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/openshift-infra#104]
### Issue 

I have installed ASB on origin 3.10 and some bundles such as postgresql db are blacklisted
when we use release-1.2 of ASB

### Results

- log of ASB

```
time="2018-09-11T05:28:21Z" level=info msg="Bundles filtered by white/blacklist filter:
\t-> openshift/dotnet\n\t-> openshift/dotnet-runtime\n\t-> openshift/httpd
\t-> openshift/jenkins\n\t-> openshift/mariadb\n\t-> openshift/mongodb
\t-> openshift/mysql\n\t-> openshift/nginx\n\t-> openshift/nodejs
\t-> openshift/perl\n\t-> openshift/php\n\t-> openshift/postgresql
\t-> openshift/python\n\t-> openshift/redis\n\t-> openshift/ruby
\t-> openshift/wildfly\n"
```

- Catalog query

```
odo catalog list services | grep dh-p
- dh-pyzip-demo-apb
- dh-proxy-config-apb
- dh-pyzip-demo-db-apb
- dh-prometheus-apb
```

**Comment by cmoulliard** [comment]
Workaround is perhaps to define a blacklist filter within the ConfigMap maybe

**Comment by cmoulliard** [comment]
> release-1.2 of ASB

The message reported hereafter indicates that the version used is not `1.2` but instead `1.3.x`

**Comment by geoand** [comment]
Have you found any ansible vars that would allow up to create a blacklist field in the configmap?

**Comment by cmoulliard** [comment]
> blacklist field in the configmap

Such var doesn't exist but it is well defined within the [ConfigMap of the project](https://goo.gl/hoN5Ww). What we observer here is a side effect about the fact that we want to use `1.2` instead of `1.3.x` and in fact, this is the latest version of broker which is deployed and under  construction for openshift 3.11 ....

**Comment by geoand** [comment]
So I guess we need to wait for a fix

**Comment by cmoulliard** [comment]
From Erik Nelson

"If you check the broker's configmap (oc edit configmap broker-config -n <BROKER_NAMESPACE>), you should see a section for registry configuration with white/black list regex. The image names need to match on the whitelist pattern otherwise they will be filtered. I believe the default pattern is .*-apb, so none of those image names will pass. Alternatively, you could just set it to ".*" and it will allow all of them through. If you change the configmap, just note you will need to redeploy the broker for those changes to be picked up. Either delete the broker's pod, or rollout the latest broker dc in the namespace."
