### ISSUE TITLE
Should this private key be on GitHub?

### ISSUE THREAD

**Issue by bbaassssiiee** [snowdrop/openshift-infra#111]
https://github.com/snowdrop/openshift-infra/blob/9c358170b1c8157fa77f3172f0d16ef99a2f56da/virtualbox/build-centos-iso/.vagrant/machines/default/virtualbox/private_key

**Comment by geoand** [comment]
Thanks for spotting this!

The key was a dummy, but should nevertheless not be there :P

**Comment by geoand** [comment]
Closed via dec2b09
