### ISSUE TITLE
Move openshift template to install web site within the playbook

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/openshift-infra#123]
## Request

I propose to move the [OpenShift template to install the web site](https://github.com/snowdrop/snowdrop-site-angular/blob/master/openshift/snowdrop-site.yaml) to the playbook [`deploy_snowdrop_site`](ansible/playbook/roles/deploy_snowdrop_site) as we must now integrate within the route the CA, Site Certificate and Private Key like to deploy out web server as HTTP or HTTPS Site

WDYT @geoand ?

**Comment by geoand** [comment]
I actually don't agree, since this playbook repository is supposed to be somewhat generic.
We should use a dedicated and private repo if we actually need a playbook for deploying the website

**Comment by cmoulliard** [comment]
And do you plan then to secure the CA, Site Cert and Private key files to be used when the Edge OpenShift route should be then created ?

**Comment by geoand** [comment]
How would be secure if it were in this repo? 
IMHO having it here is both less secure and out of place.

We could move it to an internal repo and then use whatever protection mechanism we deem necessary on that repo

**Comment by cmoulliard** [comment]
My idea is to encrypt the files using ansible-vault - https://docs.ansible.com/ansible/2.4/vault.html#encrypting-unencrypted-files. In this case, the only thing to keep secret is the password needed to generate the vault key

**Comment by geoand** [comment]
That still leaves the problem that the website is very specific while these playbooks are generic.
If you want to go down this route, we can do it, I'm just saying I don't think it's the best way to go

**Comment by cmoulliard** [comment]
The playbook is not very generic as it already modify the template - see changeme

https://github.com/snowdrop/openshift-infra/blob/master/ansible/playbook/roles/deploy_snowdrop_site/tasks/main.yml#L15-L19

What I'm proposing is to have 3 encrypted vars in order to replace within the route definition the part to add the CA, site cert and private key. If we do that, we could keep the template within the original snowdrop-angular-site github project but under another template as we must create a edge route ...

**Comment by geoand** [comment]
OK, sounds good

**Comment by cmoulliard** [comment]
As no ansible vault role exists, then how will it be then possible to decrypt encryted files ...

**Comment by geoand** [comment]
I have never used Ansible vault, but I am guessing that some command line flag will allow us to pass the decryption key and then everything will work?
I would have to look into it

**Comment by cmoulliard** [comment]
That could help us - https://gist.github.com/tristanfisher/e5a306144a637dc739e7

**Comment by cmoulliard** [comment]
I looked to the best practice guide but I'm not yet sure what could be the benefit to use this approach

```
A best practice approach for this is to start with a group_vars/ subdirectory named after the group. Inside of this subdirectory, create two files named vars and vault. Inside of the vars file, define all of the variables needed, including any sensitive ones. Next, copy all of the sensitive variables over to the vault file and prefix these variables with vault_. You should adjust the variables in the vars file to point to the matching vault_ variables using jinja2 syntax, and ensure that the vault file is vault encrypted.
```

**Comment by geoand** [comment]
That indeed doesn't sounds terribly helpful. I will take a look tomorrow
