### ISSUE TITLE
Make role k8s and openshift compatible

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/openshift-infra#126]
## Feature request

Would it be possible that we generalize this role `install_component_crd_operator` to make it deployable on k8s or openshift

We could have a boolean value used with when

Example for the dependencies
```
---
dependencies:
  - { role: openshift_env, when: isOpenshift | default(true) | bool }
```

Command
```
ansible-playbook -i inventory/simple_host playbook/k8s.yml --tags tekton_pipelines -e remove=true -e isOpenshift=false
```

WDYT @geoand

**Comment by geoand** [comment]
I is certainly possible, but not easy.

The reason is that we have made all post installation roles openshift specific (which made perfect sense for the scope of the project when we made that decision).
So to do this is a maintenance way would probably require some fairly significant refactoring, which in turn would require time 😁

**Comment by cmoulliard** [comment]
That should not be a big work for the `install_component_crd_operator` as 3 things should be changed:

- have a var to specify which client to be used: oc, kubectl. 
- create a project vs namespace when we deploy on k8s or openshift
- have a bool check to use the `- { role: openshift_env, when: isOpenshift | default(true) | bool }`

**Comment by geoand** [comment]
I would prefer not to go down such a route. It will make things hard to maintain if the same sort of strategy is applied to the other roles as well.

If you want to go ahead and implement it for this role only, I guess that is fine. But if we plan to have first class k8s support for the other roles as well, we need to do it differently and more generally.

**Comment by cmoulliard** [comment]
I will only do that for the component operator role and tekton as both are needed on ocp or k8s

**Comment by geoand** [comment]
In that case, I have no objections :). 

It looks like you have it figured out, but don't hesitate to ping me if you want to check it out.

**Comment by cmoulliard** [comment]
I will then add the `isOpenshift` bool var for the 2 mentioned roles without defining what should be the value of the var

```
 ansible-playbook -i inventory/simple_host playbook/k8s.yml --tags tekton_pipelines                     

PLAY [masters] *******************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************************************************************************************************
ok: [192.168.99.50]

TASK [openshift_env : set_fact] **************************************************************************************************************************************************************************************************************************************
fatal: [192.168.99.50]: FAILED! => {"msg": "The conditional check 'isOpenshift | bool' failed. The error was: error while evaluating conditional (isOpenshift | bool): 'isOpenshift' is undefined\n\nThe error appears to be in '/Users/dabou/Code/snowdrop/openshift-infra/ansible/playbook/roles/openshift_env/tasks/main.yml': line 13, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- set_fact:\n  ^ here\n"}

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************************************
192.168.99.50              : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

ansible-playbook -i inventory/simple_host playbook/k8s.yml --tags tekton_pipelines -e isOpenshift=false
...
```

WDYT @geoand  ?

**Comment by geoand** [comment]
Yes, that sounds like the best to way to control the flow for this particular use case

**Comment by geoand** [comment]
I just saw the error message, sorry I missed it. I see the same error as well so I'll check and see how it can be fixed

**Comment by cmoulliard** [comment]
implemented
