### ISSUE TITLE
Service Catalog can't be deployed after running cluster role

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/openshift-infra#67]
Steps

```
ansible-playbook playbook/generate_inventory.yml -e ip_address=192.168.99.50 -e type=simple
ansible-playbook -i inventory/simple_host playbook/cluster.yml --tags "up"
ansible-playbook -i inventory/simple_host openshift-ansible/playbooks/openshift-service-catalog/config.yml -e openshift_master_unsupported_embedded_etcd=true
```
Error
```
TASK [Evaluate groups - Fail if no etcd hosts group is defined] ******************************************************************************************************
fatal: [localhost]: FAILED! => {
"changed": false, 
"msg": "Running etcd as an embedded service is no longer supported. If this is a new install please define an 'etcd' group with either one, three or five hosts.
These hosts may be the same hosts as your masters. If this is an upgrade please see https://docs.openshift.com/container-platform/latest/install_config/upgrading/migrating_embedded_etcd.html for documentation on how to migrate from embedded to external etcd.
"}
        to retry, use: --limit @/Users/dabou/Code/snowdrop/cloud-native/temp/openshift-infra/ansible/openshift-ansible/playbooks/openshift-service-catalog/config.retry
```

**Comment by geoand** [comment]
I would suggest you give this a look first, since I have very little service broker experience and will probably take a lot longer to figure out the issue.

**Comment by cmoulliard** [comment]
issue reported `Fail if no etcd hosts group is defined` has nothing to do with Service Catalog but due to missing parameter not defined within the `simple` inventory file ...

**Comment by cmoulliard** [comment]
I will try using the `cloud` inventory template and `ansible-playbook -i inventory/cloud_host playbook/cluster.yml --tags "up"`

**Comment by geoand** [comment]
Interesting...

We use the simple inventory file since the only that is needed for all the other roles is the IP address of the machine.

I propose that we keep it simple, and document that the `service-catalog` can only be used with the cloud_inventory

**Comment by geoand** [comment]
Using the `cloud_inventory` does work with all roles, that is not a problem

**Comment by cmoulliard** [comment]
No luck as playbook reports 
```
TASK [openshift_service_catalog : Label 192.168.99.50 for APIServer and controller deployment] ***********************************************************************
fatal: [192.168.99.50]: FAILED! => {"changed": false, 
"msg": {"cmd": "/usr/local/bin/oc label node 192.168.99.50 node-role.kubernetes.io/master=true --overwrite", "results": {}, "returncode": 1, 
"stderr": "Error from server (NotFound): nodes \"192.168.99.50\" not found\n", "stdout": ""}}
```
This is because when `oc cluster up` is launched using our playbook's role, then the node is created using `localhost` instead of the ip `192.168.99.50`

```
oc get nodes
NAME        STATUS    ROLES     AGE       VERSION
localhost   Ready     <none>    1m        v1.9.1+a0ce1bc657
```

**Comment by geoand** [comment]
Interesting... 

Although I can definitely understand why would want to have the `service-broker` work on a cluster provisioned with the `cluster` role, currently it seems to pose too many problems.
I propose that clearly document that the `service-catalog` role only be used on a cluster provisioned with `openshift-ansibile` using the `cloud_host` inventory file

**Comment by cmoulliard** [comment]
I agree. We will document as you suggested that servicecatalog can't be used with `cluster` role

**Comment by geoand** [comment]
Sounds good to me :)
