### ISSUE TITLE
Delete symbolic link of the redhat cert file under docker registry

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/openshift-infra#93]
Post creation of a new Openshift cluster using Ansible OpenShift playbooks, I had several times to delete this symbolic file within the linux vm 

`/etc/docker/certs.d/registry.access.redhat.com/redhat-ca.crt`

 in order to let the openshift server to download the openjdk1.8 image from the registry.access.redhat.com server

Remark : That was working pretty well 2 weeks ago

**Comment by geoand** [comment]
I can confirm this bug. 

I was able to reproduce it on an Openshift 3.9 cluster that was installed using `openshift-ansible` on a clean CentOS 7 machine

**Comment by geoand** [comment]
FWIW, the `openshif-ansible` playbook worked just fine up until a few days ago

**Comment by cmoulliard** [comment]
Problem is that the symbolic link points to a file which doesnot exist anymore

```
lrwxrwxrwx. 1 root root 27 May 18 16:10 /etc/docker/certs.d/registry.access.redhat.com/redhat-ca.crt -> /etc/rhsm/ca/redhat-uep.pem

[root@cloud ~]# cat /etc/rhsm/ca/redhat-uep.pem
cat: /etc/rhsm/ca/redhat-uep.pem: No such file or directory
```

**Comment by geoand** [comment]
This is most likely a bug in `openshift-ansible` since we haven't changed anything, nor are we doing anything regarding the certificates
Would you like me to open a ticket there?

**Comment by cmoulliard** [comment]
According to the doc - https://centos.pkgs.org/7/centos-x86_64/subscription-manager-rhsm-certificates-1.20.11-1.el7.centos.x86_64.rpm.html, the files created are available under

```
[root@cloud ~]# ls -la /etc/rhsm/ca/
total 0
drwxr-xr-x. 2 root root  6 Apr 13 15:34 .
drwxr-xr-x. 3 root root 16 May 18 16:28 ..
```

biut as we can see there are no cert ....

**Comment by geoand** [comment]
Weird indeed....

**Comment by geoand** [comment]
I don't think that the package is causing the problem. 
I launched `openshift-ansible` after I removed the package, and the erroneous symlink is still created

**Comment by cmoulliard** [comment]
Temporary workaround is to delete the symbolic link and then the docker client will be able to download a docker image from the red hat docker registry

**Comment by geoand** [comment]
Yes, that is of course the temporary solution, but I'm trying to figure out why the symlink is wrong.
I'll do a little more digging and see if I can find anything

**Comment by geoand** [comment]
One of the packages is definitely to blame.
I see `/etc/docker/certs.d/` being created when the VM comes up

**Comment by geoand** [comment]
The `docker` package is the problematic package....

It's the one creating the symlink
